environments:
  - name: Dev
    provisioner: gcp
    iacPolicy: "CC Best Practice"
    iacRoot: "terraform/dev"

pipelines:
  skaffold-deploy:
    - gke-skaffold@1

applications:
  msdemo:
    displayName: "Online Boutique"
    srcRoot: "."
    pipeline: skaffold-deploy

deployments:
  dev:
    endpoints:
      - msdemo
    environment:
      name: Dev
      inputs:
        gke_name: msdemo_online_boutique
    applications:
      msdemo:
        env:
          CLUSTER_NAME: ${terraform.gke.value.name}
        pipelineInputs:
          gke_cluster_name: "$$CLUSTER_NAME"
    output:
      frontend-endpoint:
        command: sleep 60; kubectl get --no-headers -o custom-columns=EXTERNAL-IP:.status.loadBalancer.ingress[0].ip service frontend-external
